inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - bin/**

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/LineLength:
  Max: 132
Metrics/MethodLength:
  Severity: warning

Naming/FileName:
  Enabled: false

# Rationale: allow Weirich-style blocks
Style/BlockDelimiters:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
